name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linting:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.8

      - name: Install Pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install root dependencies
        run: |
          pipenv install --dev --skip-lock

      - name: Run linting
        run: |
          make lint
